# Generated by Django 3.2.9 on 2021-11-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
