# Generated by Django 3.2.9 on 2021-11-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_delete_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='director',
        ),
    ]
