# Generated by Django 3.2.9 on 2021-11-16 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('school', '0004_remove_school_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='director',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.director'),
        ),
    ]
