# Generated by Django 3.2.9 on 2021-11-16 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211116_2210'),
        ('school', '0005_school_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='School',
            name='director',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.director'),
        ),
    ]
