# Generated by Django 3.2.9 on 2021-11-17 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211117_0814'),
        ('school', '0006_alter_school_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='director',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director', to='account.director'),
        ),
    ]
