# Generated by Django 3.2.9 on 2021-11-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211117_0814'),
        ('school', '0007_alter_school_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='assistants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistants', to='account.assistant'),
        ),
    ]
