# Generated by Django 3.2.9 on 2021-11-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211117_0814'),
        ('school', '0008_school_assistants'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='account.Teacher'),
        ),
    ]
