# Generated by Django 3.2.9 on 2021-11-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20211117_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='assistants',
        ),
    ]
