# Generated by Django 3.2.9 on 2021-11-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_assistantmodel_shcools'),
        ('school', '0013_remove_school_assistants'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='assistants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.assistant'),
        ),
    ]
