# Generated by Django 3.2.9 on 2021-11-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_school_assistants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='assistants',
        ),
    ]
