# Generated by Django 3.2.9 on 2021-11-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211117_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmodel',
            name='shcools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school', to='account.assistant'),
        ),
    ]
