# Generated by Django 3.2.9 on 2021-11-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_assistantmodel_shcools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantmodel',
            name='shcools',
        ),
    ]
