# Generated by Django 3.2.9 on 2021-11-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_school_assistants'),
        ('account', '0007_remove_assistantmodel_shcools'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmodel',
            name='shcools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school', to='school.school'),
        ),
    ]
